#lang racket
(require "monitor.rkt")
(define test-mon
  (make-monitor (public test)
                (define n 0)
                (define test
                  (λ (idx)
                    (set! n (add1 n))
                    (display (~a idx" connected."))
                    (sleep 0.5) (display ".")
                    (sleep 0.5) (display ".")
                    (sleep 0.5) (display ".")
                    (sleep 0.5) (display ".")
                    (sleep 0.5) (display ".")
                    (display (~a ""n"th thread to connect.\n"))
                    (sleep 0.5)))))
(let loop ([n 5])
  (thread (λ () (let t-loop () 
                  (sleep 0.5) 
                  (monitor-call test-mon test n)
                  (t-loop))))
  (unless (zero? n) (loop (sub1 n))))
